INSERT INTO PUBLIC.WATCHLIST (FILM_ID, ACCOUNT_ID) VALUES (1, 2);
INSERT INTO PUBLIC.WATCHLIST (FILM_ID, ACCOUNT_ID) VALUES (2, 2);
INSERT INTO PUBLIC.WATCHLIST (FILM_ID, ACCOUNT_ID) VALUES (3, 2);
INSERT INTO PUBLIC.WATCHLIST (FILM_ID, ACCOUNT_ID) VALUES (4, 2);
INSERT INTO PUBLIC.WATCHLIST (FILM_ID, ACCOUNT_ID) VALUES (5, 2);