INSERT INTO PUBLIC.ACCOUNTS_TO_ROLES (ACCOUNT_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO PUBLIC.ACCOUNTS_TO_ROLES (ACCOUNT_ID, ROLE_ID) VALUES (2, 1);
INSERT INTO PUBLIC.ACCOUNTS_TO_ROLES (ACCOUNT_ID, ROLE_ID) VALUES (2, 2);