INSERT INTO PUBLIC.COUNTRIES (NAME) VALUES ('Estados Unidos');
INSERT INTO PUBLIC.COUNTRIES (NAME) VALUES ('España');
INSERT INTO PUBLIC.COUNTRIES (NAME) VALUES ('Francia');
INSERT INTO PUBLIC.COUNTRIES (NAME) VALUES ('Italia');
INSERT INTO PUBLIC.COUNTRIES (NAME) VALUES ('Brasil');