INSERT INTO PUBLIC.COUNTRIES (NAME) VALUES ('Estados Unidos');
INSERT INTO PUBLIC.COUNTRIES (NAME) VALUES ('España');
INSERT INTO PUBLIC.COUNTRIES (NAME) VALUES ('Francia');
INSERT INTO PUBLIC.COUNTRIES (NAME) VALUES ('Italia');
INSERT INTO PUBLIC.COUNTRIES (NAME) VALUES ('Brasil');
INSERT INTO PUBLIC.COUNTRIES (NAME) VALUES ('Reino Unido');
INSERT INTO PUBLIC.COUNTRIES (NAME) VALUES ('Nueva Zelanda');
INSERT INTO PUBLIC.COUNTRIES (NAME) VALUES ('Canadá');